export const SET_PRODUCTS = 'SET_PRODUCTS';
export const DELETE_PRODUCTS = 'DELETE_PRODUCTS';
export const ADD_PRODUCT_TO_CART = 'ADD_PRODUCT_TO_CART';
export const SET_DISPLAY_PRODUCT = 'SET_DISPLAY_PRODUCT';
export const BACK_TO_HOME_PAGE = 'BACK_TO_HOME_PAGE';